M48
; DRILL file {KiCad 9.0.7} date 2026-02-23T15:22:54-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-23T15:22:54-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.251
%
G90
G05
T1
X62.55Y-85.65
X62.55Y-90.15
T2
X110.604Y-83.158
X110.604Y-92.81
M30
